"""
mpc_distillation.py – MPC + Kalman filter for the distillation column model.

State-space matrices (nx=15, nu=2, ny=3, Ts=1 min) are loaded from CSV files
generated by dist_model_dt.py.  Variables are in deviation-variable form
(deviations from a nominal operating point), scaled so that typical moves
span roughly -100 to +100.

Inputs (manipulated variables, MV):
    u[0] = V  boilup rate deviation        [% of operating range]
    u[1] = D  distillate draw deviation    [% of operating range]

Outputs (controlled variables, CV):
    y[0] = OHt  overhead temperature       [% of operating range]
    y[1] = L    reflux rate                [% of operating range]
    y[2] = BmT  bottom temperature         [% of operating range]

DC gains of the original model (with inputs at ±100 → outputs ≈ ±100):
    OHt/V = -0.20,  OHt/D = +0.30
    L/V   = +1.00,  L/D   = -1.00
    BmT/V = +1.00,  BmT/D = +1.20

Simulation events:
    t = SP_TIME       – setpoint change: OHt → +20, BmT → -15
    t = DIST_V_TIME   – unmeasured step disturbance on V (+10)
    t = DIST_D_TIME   – unmeasured step disturbance on D (-10)

Usage:
    python mpc_distillation.py
"""

import numpy as np
import casadi as ca
import do_mpc
import matplotlib.pyplot as plt
import matplotlib.lines as mlines

# ── Configuration ─────────────────────────────────────────────────────────
DATA_DIR = "src/dist_model_dt"  # folder containing A/B/C/D.csv
Ts = 1.0  # sampling period [min]
N_SIM = 150  # total simulation steps
N_HORIZON = 30  # MPC prediction horizon [steps]

# Setpoint change at t = SP_TIME
SP_TIME = 30  # [min]
OHt_SP = 2.5  # new OHt setpoint after change
L_SP = 0.0  # L setpoint after change
BmT_SP = 2.5  # new BmT setpoint after change

# Step disturbances on plant inputs (not known to MPC or estimator)
DIST_V_TIME = 70  # [min] start of step disturbance on V
DIST_V_AMP = 0.0  # [% units] magnitude of V disturbance
DIST_D_TIME = 100  # [min] start of step disturbance on D
DIST_D_AMP = 0.0  # [% units] magnitude of D disturbance

# Input hard constraints [% units]
U_MIN = -100.0
U_MAX = 100.0

# MPC cost weights
Q_WEIGHTS = np.array([10.0, 0.0, 10.0])  # output tracking: OHt, L, BmT
R_WEIGHTS = np.array([0.0, 0.0])  # input cost:  V, D
DU_WEIGHTS = np.array([1.0, 1.0])  # input rate-of-change cost

# Kalman filter noise parameters
PROC_NOISE_STD = 1e-2  # process noise std dev (applied to all states)
MEAS_NOISE_STD = 0.0  # measurement noise std dev (0 = perfect measurements)

# ── Load state-space matrices ─────────────────────────────────────────────────
A = np.loadtxt(f"{DATA_DIR}/A.csv", delimiter=",")
B = np.loadtxt(f"{DATA_DIR}/B.csv", delimiter=",")
C = np.loadtxt(f"{DATA_DIR}/C.csv", delimiter=",")
D_mat = np.loadtxt(f"{DATA_DIR}/D.csv", delimiter=",")

nx = A.shape[0]  # 15  (states)
nu = B.shape[1]  # 2   (inputs:  V, D)
ny = C.shape[0]  # 3   (outputs: OHt, L, BmT)

print(f"Loaded model: nx={nx}, nu={nu}, ny={ny}, Ts={Ts} min")

# ── 1. do_mpc model definition ────────────────────────────────────────────────
model = do_mpc.model.Model("discrete")

x = model.set_variable("_x", "x", shape=(nx, 1))
u = model.set_variable("_u", "u", shape=(nu, 1))
y_sp = model.set_variable("_tvp", "y_sp", shape=(ny, 1))

# State equation:  x(k+1) = A x(k) + B u(k)
model.set_rhs("x", ca.DM(A) @ x + ca.DM(B) @ u)

# Measurement equation:  y(k) = C x(k) + D u(k)   (D_mat = 0 for this model)
model.set_meas("y", ca.DM(C) @ x + ca.DM(D_mat) @ u)

model.setup()

# ── 2. MPC controller ─────────────────────────────────────────────────────
mpc = do_mpc.controller.MPC(model)

mpc.set_param(
    n_horizon=N_HORIZON,
    t_step=Ts,
    store_full_solution=True,
    nlpsol_opts={
        "ipopt.print_level": 0,
        "print_time": 0,
        "ipopt.sb": "yes",
    },
)

# Quadratic output-tracking and input cost
# lterm: stage cost  J_stage = e^T Q e + u^T R u
# mterm: terminal cost  J_term = e^T Q e
y_pred = ca.DM(C) @ x + ca.DM(D_mat) @ u
e = y_pred - y_sp  # output tracking error (ny × 1)

Q_ca = ca.DM(np.diag(Q_WEIGHTS))
R_ca = ca.DM(np.diag(R_WEIGHTS))

lterm = ca.mtimes([e.T, Q_ca, e]) + ca.mtimes([u.T, R_ca, u])
mterm = ca.mtimes([e.T, Q_ca, e])

mpc.set_objective(mterm=mterm, lterm=lterm)

# Penalise rate of change of inputs:  du^T * diag(DU_WEIGHTS) * du
mpc.set_rterm(u=DU_WEIGHTS)

# Input bounds
mpc.bounds["lower", "_u", "u"] = U_MIN * np.ones((nu, 1))
mpc.bounds["upper", "_u", "u"] = U_MAX * np.ones((nu, 1))

# Time-varying setpoint: looked up for every step in the prediction horizon
tvp_template_mpc = mpc.get_tvp_template()


def tvp_fun_mpc(t_now):
    for k in range(N_HORIZON + 1):
        if t_now + k * Ts >= SP_TIME:
            tvp_template_mpc["_tvp", k, "y_sp"] = np.array(
                [[OHt_SP], [L_SP], [BmT_SP]]
            )
        else:
            tvp_template_mpc["_tvp", k, "y_sp"] = np.zeros((ny, 1))
    return tvp_template_mpc


mpc.set_tvp_fun(tvp_fun_mpc)
mpc.setup()

# ── 3. Plant simulator ────────────────────────────────────────────────────
simulator = do_mpc.simulator.Simulator(model)
simulator.set_param(t_step=Ts)

tvp_template_sim = simulator.get_tvp_template()


def tvp_fun_sim(t_now):
    # y_sp is not used by the simulator dynamics; provide a consistent value.
    # The simulator TVP template is single-step (no horizon index).
    if t_now >= SP_TIME:
        tvp_template_sim["y_sp"] = np.array([[OHt_SP], [L_SP], [BmT_SP]])
    else:
        tvp_template_sim["y_sp"] = np.zeros((ny, 1))
    return tvp_template_sim


simulator.set_tvp_fun(tvp_fun_sim)
simulator.setup()

# ── 4. EKF state estimator ────────────────────────────────────────────────────
# do_mpc's built-in EKF implements the standard discrete-time Kalman filter
# predict/update cycle, using the model's CasADi expressions to evaluate the
# linearised system matrices at each step.  For this linear model A_k, C_k are
# constant, so the EKF is exactly equivalent to the classical Kalman filter.
#
# Prediction  (using only u_mpc – the estimator does not know about d):
#   x_pred = A x_hat + B u_mpc
#   P_pred = A P A^T + Q_proc
#
# Update  (y_meas is the simulator output after u_mpc + d was applied):
#   K      = P_pred C^T (C P_pred C^T + R_meas)^{-1}
#   x_hat  = x_pred + K (y_meas - C x_pred)
#   P      = (I - K C) P_pred
#
# Q_proc and R_meas are passed at every make_step() call so they can be varied
# online; here they are kept constant.

Q_proc = (PROC_NOISE_STD**2) * np.eye(nx)
R_meas = max(MEAS_NOISE_STD**2, 1e-10) * np.eye(
    ny
)  # small floor avoids singularity

estimator = do_mpc.estimator.EKF(model)
estimator.settings.t_step = Ts  # required; no set_param() method on EKF

# The EKF requires a TVP function because y_sp is declared as _tvp in the model.
# Its value does not affect A/B/C/D (linear model) but a valid CasADi structure
# must be provided at each time step.
tvp_template_ekf = estimator.get_tvp_template()


def tvp_fun_ekf(t_now):
    if t_now >= SP_TIME:
        tvp_template_ekf["y_sp"] = np.array([[OHt_SP], [L_SP], [BmT_SP]])
    else:
        tvp_template_ekf["y_sp"] = np.zeros((ny, 1))
    return tvp_template_ekf


estimator.set_tvp_fun(tvp_fun_ekf)
estimator.setup()


# ── 5. Initialisation ─────────────────────────────────────────────────────
x0 = np.zeros((nx, 1))

mpc.x0 = x0
simulator.x0 = x0
estimator.x0 = x0
estimator.P0 = np.eye(nx)
mpc.set_initial_guess()
estimator.set_initial_guess()

# Pre-allocate history arrays
t_hist = np.arange(N_SIM) * Ts
y_hist = np.zeros((N_SIM, ny))
u_hist = np.zeros((N_SIM, nu))
u_plant_hist = np.zeros((N_SIM, nu))
sp_hist = np.zeros((N_SIM, ny))

# ── 6. Closed-loop simulation ─────────────────────────────────────────────────
print("Running closed-loop MPC simulation …")

for k in range(N_SIM):
    t_now = k * Ts

    # Current setpoint (for logging)
    if t_now >= SP_TIME:
        sp_k = np.array([[OHt_SP], [L_SP], [BmT_SP]])
    else:
        sp_k = np.zeros((ny, 1))

    # --- 6a. MPC: compute optimal control action ---
    u_mpc = mpc.make_step(estimator.x0)  # uses current EKF state estimate

    # --- 6b. Unmeasured step disturbance on plant inputs ---
    d = np.zeros((nu, 1))
    if t_now >= DIST_V_TIME:
        d[0, 0] = DIST_V_AMP
    if t_now >= DIST_D_TIME:
        d[1, 0] = DIST_D_AMP

    u_plant = u_mpc + d  # actual input applied to plant (MPC unaware of d)

    # --- 6c. Simulate plant one step forward ---
    y_clean = simulator.make_step(u_plant)  # noiseless plant output

    # --- 6d. Add optional measurement noise ---
    noise = (
        MEAS_NOISE_STD * np.random.randn(ny, 1)
        if MEAS_NOISE_STD > 0
        else np.zeros((ny, 1))
    )
    y_meas = y_clean + noise

    # --- 6e. EKF: predict with u_mpc (disturbance unknown), update with y_meas ---
    estimator.make_step(y_meas, u_mpc, Q_proc, R_meas)

    # --- Store ---
    y_hist[k] = y_meas.flatten()
    u_hist[k] = u_mpc.flatten()
    u_plant_hist[k] = u_plant.flatten()
    sp_hist[k] = sp_k.flatten()

print("Simulation complete.")

# ── 7. Plotting ───────────────────────────────────────────────────────────
output_names = ["OHt [%]", "L [%]", "BmT [%]"]
input_names = ["V [%]", "D [%]"]

# Event lines: (time, label, colour)
events = [
    (SP_TIME, "SP change", "steelblue"),
    (DIST_V_TIME, "Dist V", "firebrick"),
    (DIST_D_TIME, "Dist D", "seagreen"),
]

fig, axs = plt.subplots(ny + nu, 1, figsize=(10, 9), sharex=True)
fig.suptitle("Distillation Column – MPC Closed-loop Simulation", fontsize=12)

# Outputs
for i in range(ny):
    ax = axs[i]
    ax.step(
        t_hist,
        sp_hist[:, i],
        where="post",
        linestyle="--",
        color="k",
        linewidth=1.2,
        label="setpoint",
    )
    ax.step(
        t_hist,
        y_hist[:, i],
        where="post",
        color="tab:blue",
        linewidth=1.0,
        label="output",
    )
    ax.set_ylabel(output_names[i])
    ax.legend(loc="upper right", fontsize=7)
    ax.grid(True, alpha=0.3)
    for t_ev, _, col in events:
        ax.axvline(t_ev, color=col, linestyle=":", linewidth=0.9, alpha=0.7)

# Inputs (MPC command shown solid; actual plant input shown dashed if different)
for j in range(nu):
    ax = axs[ny + j]
    ax.step(
        t_hist,
        u_hist[:, j],
        where="post",
        color="tab:orange",
        linewidth=1.2,
        label="u_mpc",
    )
    ax.step(
        t_hist,
        u_plant_hist[:, j],
        where="post",
        color="tab:red",
        linestyle="--",
        linewidth=1.0,
        label="u_plant (with dist.)",
    )
    ax.set_ylabel(input_names[j])
    ax.legend(loc="upper right", fontsize=7)
    ax.grid(True, alpha=0.3)
    for t_ev, _, col in events:
        ax.axvline(t_ev, color=col, linestyle=":", linewidth=0.9, alpha=0.7)

axs[-1].set_xlabel("Time [min]")

# Shared event legend at bottom of last axes
event_handles = [
    mlines.Line2D([], [], color=col, linestyle=":", linewidth=1.2, label=lbl)
    for _, lbl, col in events
]
axs[-1].legend(
    handles=event_handles,
    loc="lower right",
    fontsize=7,
    title="Events",
)

plt.tight_layout()
plt.show()
