"""
mpc_distillation.py – Offset-free MPC + EKF for the distillation column model.

State-space matrices (nx=15, nu=2, ny=3, Ts=1 min) are loaded from CSV files
generated by dist_model_dt.py.  Variables are in deviation-variable form
(deviations from a nominal operating point), scaled so that typical moves
span roughly -100 to +100.

Inputs (manipulated variables, MV):
    u[0] = V  boilup rate deviation        [% of operating range]
    u[1] = D  distillate draw deviation    [% of operating range]

Outputs (controlled variables, CV):
    y[0] = OHt  overhead temperature       [% of operating range]
    y[1] = L    reflux rate                [% of operating range]
    y[2] = BmT  bottom temperature         [% of operating range]

DC gains of the original model (with inputs at ±100 → outputs ≈ ±100):
    OHt/V = -0.20,  OHt/D = +0.30
    L/V   = +1.00,  L/D   = -1.00
    BmT/V = +1.00,  BmT/D = +1.20

Offset-free formulation
-----------------------
The MPC model and EKF use an AUGMENTED state  xa = [x; d_u]  that appends one
integrating disturbance state per input channel (nd = nu = 2, nxa = 17).

    Plant (truth):   x(k+1) = A x(k) + B (u(k) + d_u(k))
    Disturbance:     d_u(k+1) = d_u(k)          (random walk / integrator)

Augmented matrices built by dist_ctrl.ss_utils.augment_input_disturbances():
    Aa = [[A,  B],     Ba = [[B],     Ca = [C  0]
          [0,  I]]           [0]]

The EKF (augmented model, nxa=17) estimates both x and d_u from plant
measurements.  The MPC uses the ORIGINAL plant model (nx=15) but receives
d_hat (the EKF's disturbance estimate) as a time-varying parameter, which
feeds forward into the N-step prediction:

    x(k+j+1|k) = A x(k+j|k) + B u(k+j|k) + B d_hat(k)   j = 0..N-1

This achieves zero steady-state offset for sustained step disturbances
without enlarging the MPC optimisation problem (Pannocchia & Rawlings, 2003).

The do_mpc Simulator is NOT used; the plant is propagated directly with numpy
so that the true disturbance can be injected at the plant input without
leaking into the estimator model.

Simulation events:
    t = SP_TIME       – setpoint change
    t = DIST_V_TIME   – unmeasured step disturbance on V
    t = DIST_D_TIME   – unmeasured step disturbance on D

Usage:
    python mpc_distillation.py
"""

from pathlib import Path
import numpy as np
import casadi as ca
import do_mpc
import matplotlib.pyplot as plt
import matplotlib.transforms as mtransforms
from dist_ctrl.ss_utils import augment_input_disturbances
from dist_ctrl.variables import VAR_INFO

# ── Configuration ─────────────────────────────────────────────────────────
DATA_DIR = Path("src/dist_model_dt")  # folder containing A/B/C/D.csv
PLOT_DIR = Path("plots")  # folder to save plot images
PLOT_DIR.mkdir(parents=True, exist_ok=True)

# Simulation parameters
Ts = 1.0  # sampling period [min]
N_SIM = 150  # total simulation steps

# Setpoint change at t = SP_TIME
SP_TIME = 30  # [min]
OHt_SP = 2.5  # new OHt setpoint after change
L_SP = 0.0  # L setpoint after change
BmT_SP = 2.5  # new BmT setpoint after change

# Step disturbances on plant inputs (not known to MPC or estimator)
DIST_V_TIME = 70  # [min] start of step disturbance on V
DIST_V_AMP = 10.0  # [% units] magnitude of V disturbance
DIST_D_TIME = 100  # [min] start of step disturbance on D
DIST_D_AMP = 10.0  # [% units] magnitude of D disturbance

# Input hard constraints [% units]
U_MIN = -100.0
U_MAX = 100.0

# MPC parameters
N_HORIZON = 20  # MPC prediction horizon [steps]

# MPC cost function weights
Q_WEIGHTS = np.array([10.0, 0.0, 10.0])  # output tracking: OHt, L, BmT
R_WEIGHTS = np.array([0.0, 0.0])  # input cost:  V, D
DU_WEIGHTS = np.array([1.0, 1.0])  # input rate-of-change cost

# Kalman filter noise parameters
PROC_NOISE_STD = 1e-2  # process noise std dev for plant states
DIST_NOISE_STD = (
    1.0  # process noise std dev for disturbance states (drives EKF tracking)
)
MEAS_NOISE_STD = 0.0  # measurement noise std dev (0 = perfect measurements)

# ── Load state-space matrices ────────────────────────────────────────────────
A = np.loadtxt(f"{DATA_DIR}/A.csv", delimiter=",")
B = np.loadtxt(f"{DATA_DIR}/B.csv", delimiter=",")
C = np.loadtxt(f"{DATA_DIR}/C.csv", delimiter=",")
D_mat = np.loadtxt(f"{DATA_DIR}/D.csv", delimiter=",")

nx = A.shape[0]  # 15  (plant states)
nu = B.shape[1]  # 2   (inputs:  V, D)
ny = C.shape[0]  # 3   (outputs: OHt, L, BmT)

# Augmented model: xa = [x; d_u], nd = nu disturbance states, nxa = nx + nd
Aa, Ba, Ca, Da = augment_input_disturbances(A, B, C, D_mat)
nd = nu  # one integrating disturbance state per input
nxa = nx + nd  # 17

print(f"Loaded model: nx={nx}, nu={nu}, ny={ny}, Ts={Ts} min")
print(
    f"Augmented model: nxa={nxa} "
    f"(plant states + {nd} input disturbance states)"
)

# ── 1a. MPC model (original plant, nx=15, with d_hat as TVP) ─────────────────
# d_hat is the EKF's current disturbance estimate, treated as a constant
# feedforward over the prediction horizon:  x+ = A x + B u + B d_hat
mpc_model = do_mpc.model.Model("discrete")

x = mpc_model.set_variable("_x", "x", shape=(nx, 1))
u = mpc_model.set_variable("_u", "u", shape=(nu, 1))
y_sp = mpc_model.set_variable("_tvp", "y_sp", shape=(ny, 1))
d_hat = mpc_model.set_variable("_tvp", "d_hat", shape=(nu, 1))

mpc_model.set_rhs("x", ca.DM(A) @ x + ca.DM(B) @ u + ca.DM(B) @ d_hat)
mpc_model.set_meas("y", ca.DM(C) @ x)

mpc_model.setup()

# ── 1b. EKF model (augmented, nxa=17, no TVP) ────────────────────────────────
# The EKF estimates xa = [x; d_u] from measurements.  It uses only u_mpc for
# its prediction; the unknown disturbance d is corrected via the innovation.
ekf_model = do_mpc.model.Model("discrete")

xa = ekf_model.set_variable("_x", "xa", shape=(nxa, 1))
u_ekf = ekf_model.set_variable("_u", "u", shape=(nu, 1))

ekf_model.set_rhs("xa", ca.DM(Aa) @ xa + ca.DM(Ba) @ u_ekf)
ekf_model.set_meas("y", ca.DM(Ca) @ xa)

ekf_model.setup()

# ── 2. MPC controller ─────────────────────────────────────────────────────
mpc = do_mpc.controller.MPC(mpc_model)

mpc.set_param(
    n_horizon=N_HORIZON,
    t_step=Ts,
    store_full_solution=True,
    nlpsol_opts={
        "ipopt.print_level": 0,
        "print_time": 0,
        "ipopt.sb": "yes",
    },
)

# Quadratic output-tracking and input cost
# lterm: stage cost  J_stage = e^T Q e + u^T R u
# mterm: terminal cost  J_term = e^T Q e
# Note: d_hat feeds into the dynamics (via RHS) but not the cost directly.
y_pred = ca.DM(C) @ x
e = y_pred - y_sp  # output tracking error (ny × 1)

Q_ca = ca.DM(np.diag(Q_WEIGHTS))
R_ca = ca.DM(np.diag(R_WEIGHTS))

lterm = ca.mtimes([e.T, Q_ca, e]) + ca.mtimes([u.T, R_ca, u])
mterm = ca.mtimes([e.T, Q_ca, e])

mpc.set_objective(mterm=mterm, lterm=lterm)

# Penalise rate of change of inputs:  du^T * diag(DU_WEIGHTS) * du
mpc.set_rterm(u=DU_WEIGHTS)

# Input bounds
mpc.bounds["lower", "_u", "u"] = U_MIN * np.ones((nu, 1))
mpc.bounds["upper", "_u", "u"] = U_MAX * np.ones((nu, 1))

# Time-varying parameters: setpoint y_sp and disturbance feedforward d_hat.
# d_hat_now is updated from the EKF each step before mpc.make_step() is called.
# For an integrating disturbance model the best prediction over the horizon is
# the current estimate (d_u(k+j) = d_u(k) for all j), so d_hat is constant.
d_hat_now = np.zeros((nu, 1))  # mutable; updated in simulation loop
tvp_template_mpc = mpc.get_tvp_template()


def tvp_fun_mpc(t_now):
    for k in range(N_HORIZON + 1):
        if t_now + k * Ts >= SP_TIME:
            tvp_template_mpc["_tvp", k, "y_sp"] = np.array(
                [[OHt_SP], [L_SP], [BmT_SP]]
            )
        else:
            tvp_template_mpc["_tvp", k, "y_sp"] = np.zeros((ny, 1))
        tvp_template_mpc["_tvp", k, "d_hat"] = (
            d_hat_now  # constant over horizon
        )
    return tvp_template_mpc


mpc.set_tvp_fun(tvp_fun_mpc)
mpc.setup()

# ── 3. Plant simulation (numpy) ──────────────────────────────────────────────
# The do_mpc Simulator is not used because its model would be the augmented
# one,
# which has no mechanism for injecting the true (unknown) disturbance.  Instead
# the plant is propagated directly:
#   x_plant(k+1) = A x_plant(k) + B u_plant(k)   [u_plant = u_mpc + d]
#   y(k)         = C x_plant(k)
x_plant = np.zeros((nx, 1))

# ── 4. EKF state estimator (augmented model, nxa=17) ─────────────────────────
# The EKF uses ekf_model (Aa, Ba, Ca) to estimate xa = [x; d_u].
# It receives only u_mpc for prediction; the unknown disturbance d is corrected
# through the measurement innovation.  Prediction / update equations:
#
#   Predict:  xa_pred = Aa xa + Ba u_mpc
#             P_pred  = Aa P Aa^T + Q_proc
#   Update:   K       = P_pred Ca^T (Ca P_pred Ca^T + R_meas)^{-1}
#             xa_hat  = xa_pred + K (y_meas - Ca xa_pred)
#             P       = (I - K Ca) P_pred
#
# Q_proc: block-diagonal — small for plant states (trust the model), larger for
# disturbance states (allow the EKF to track slow-moving disturbances).
# Q_proc and R_meas are passed at every make_step() call.

Q_proc = np.block(
    [
        [(PROC_NOISE_STD**2) * np.eye(nx), np.zeros((nx, nd))],
        [np.zeros((nd, nx)), (DIST_NOISE_STD**2) * np.eye(nd)],
    ]
)
R_meas = max(MEAS_NOISE_STD**2, 1e-10) * np.eye(ny)

estimator = do_mpc.estimator.EKF(ekf_model)
estimator.settings.t_step = Ts  # required; no set_param() on EKF

# ekf_model has no TVP variables so no tvp_fun is needed
estimator.setup()


# ── 5. Initialisation ─────────────────────────────────────────────────────
mpc.x0 = np.zeros((nx, 1))
mpc.set_initial_guess()

estimator.x0 = np.zeros((nxa, 1))  # [x; d_u], all zero
estimator.P0 = np.eye(nxa)
estimator.set_initial_guess()

# Pre-allocate history arrays
t_hist = np.arange(N_SIM) * Ts
y_hist = np.zeros((N_SIM, ny))
u_hist = np.zeros((N_SIM, nu))
u_plant_hist = np.zeros((N_SIM, nu))
sp_hist = np.zeros((N_SIM, ny))

# ── 6. Closed-loop simulation ─────────────────────────────────────────────
print("Running closed-loop MPC simulation …")

for k in range(N_SIM):
    t_now = k * Ts

    # Current setpoint (for logging)
    if t_now >= SP_TIME:
        sp_k = np.array([[OHt_SP], [L_SP], [BmT_SP]])
    else:
        sp_k = np.zeros((ny, 1))

    # --- 6a. Extract EKF estimates and update MPC disturbance feedforward ---
    xa_hat = ca.DM(estimator.x0).full()  # (nxa × 1) numpy array
    x_hat = xa_hat[:nx]  # plant state estimate
    d_hat_now[:] = xa_hat[nx:]  # disturbance estimate, fed to MPC via TVP

    # --- 6b. MPC: compute optimal control action ---
    u_mpc = mpc.make_step(x_hat)

    # --- 6c. Unmeasured step disturbance on plant inputs ---
    d = np.zeros((nu, 1))
    if t_now >= DIST_V_TIME:
        d[0, 0] = DIST_V_AMP
    if t_now >= DIST_D_TIME:
        d[1, 0] = DIST_D_AMP

    u_plant = (
        u_mpc + d
    )  # actual input applied to plant (MPC / EKF unaware of d)

    # --- 6d. Propagate plant one step (numpy) ---
    x_plant = A @ x_plant + B @ u_plant
    y_clean = C @ x_plant

    # --- 6e. Add optional measurement noise ---
    noise = (
        MEAS_NOISE_STD * np.random.randn(ny, 1)
        if MEAS_NOISE_STD > 0
        else np.zeros((ny, 1))
    )
    y_meas = y_clean + noise

    # --- 6f. EKF: predict with u_mpc (disturbance unknown), update with y_meas
    estimator.make_step(y_meas, u_mpc, Q_proc, R_meas)

    # --- Store ---
    y_hist[k] = y_meas.flatten()
    u_hist[k] = u_mpc.flatten()
    u_plant_hist[k] = u_plant.flatten()
    sp_hist[k] = sp_k.flatten()

print("Simulation complete.")

# ── 7. Plotting ───────────────────────────────────────────────────────
output_vars = ["OHt", "L", "BmT"]
input_vars = ["V", "D"]
output_labels = [f"{v} [{VAR_INFO[v]['units']}]" for v in output_vars]
output_titles = [VAR_INFO[v]["name"] for v in output_vars]
input_labels = [f"{v} [{VAR_INFO[v]['units']}]" for v in input_vars]
input_titles = [VAR_INFO[v]["name"] for v in input_vars]

# Event lines: (time, label, colour) — vertical dotted lines on every subplot;
# text labels placed at the top of the first (upper) subplot only.
events = [
    (SP_TIME, "SP change", "steelblue"),
    (DIST_V_TIME, "Dist V", "firebrick"),
    (DIST_D_TIME, "Dist D", "seagreen"),
]

fig, axs = plt.subplots(ny + nu, 1, figsize=(8, 9), sharex=True)
fig.suptitle("Distillation Column – MPC Closed-loop Simulation", fontsize=12)

# Outputs
for i in range(ny):
    ax = axs[i]
    ax.step(
        t_hist,
        sp_hist[:, i],
        where="post",
        linestyle="--",
        color="k",
        label="setpoint",
    )
    ax.step(
        t_hist,
        y_hist[:, i],
        where="post",
        color="tab:blue",
        linewidth=1.0,
        label="output",
    )
    ax.set_ylabel(output_labels[i])
    ax.set_title(output_titles[i], fontsize=9)
    ax.legend(loc="upper right", fontsize=7)
    ax.grid(True, alpha=0.3)
    for t_ev, _, col in events:
        ax.axvline(t_ev, color=col, linestyle=":", linewidth=0.9, alpha=0.7)

# Text labels for events at the top of the first subplot.
# Blended transform: x in data coordinates, y in axes fraction (0=bottom, 1=top)
# so labels sit at the axes top edge regardless of the y-scale.
ax0 = axs[0]
top_trans = mtransforms.blended_transform_factory(ax0.transData, ax0.transAxes)
for t_ev, lbl, col in events:
    ax0.text(
        t_ev + 0.5,
        0.97,
        lbl,
        transform=top_trans,
        color=col,
        fontsize=7,
        va="top",
        ha="left",
        clip_on=True,
    )

# Inputs (MPC command shown solid; actual plant input shown dashed)
for j in range(nu):
    ax = axs[ny + j]
    ax.step(
        t_hist,
        u_hist[:, j],
        where="post",
        color="tab:orange",
        label="u_mpc",
    )
    ax.step(
        t_hist,
        u_plant_hist[:, j],
        where="post",
        color="tab:red",
        linestyle="--",
        linewidth=1.0,
        label="u_plant (with dist.)",
    )
    ax.set_ylabel(input_labels[j])
    ax.set_title(input_titles[j], fontsize=9)
    ax.legend(loc="upper right", fontsize=7)
    ax.grid(True, alpha=0.3)
    for t_ev, _, col in events:
        ax.axvline(t_ev, color=col, linestyle=":", linewidth=0.9, alpha=0.7)

axs[-1].set_xlabel("Time [min]")

plt.tight_layout()
filename = "mpc_dist_sim.png"
plt.savefig(PLOT_DIR / filename, dpi=300)
plt.show()
