"""
Unit tests for the Skogestad-Morari Column A nonlinear distillation model
(src/dist_model_cola_cas/cola_model.py and cola_lv_model.py).

Reference values for xprime were generated by calling the original MATLAB
implementation colamod.m under GNU Octave:

    cd src/dist_model_cola_m
    octave --no-gui --eval "xprime = colamod(t, X, U); ..."

Test cases
----------
1. Uniform state (all compositions = 0.5, all holdups = M0 = 0.5),
   nominal inputs.  Only reboiler and condenser compositions move; all
   holdup derivatives are zero.

2. Linearly varying composition profile (0.1 at reboiler → 0.9 at
   condenser), all holdups at nominal, nominal inputs.  All holdup
   derivatives are zero; composition derivatives are non-trivial on
   every stage.

3. Same state as case 2 but with reflux LT perturbed to 3.0
   (nominal is 2.70629).  Tray 39 and condenser holdup derivatives
   become non-zero.
"""

import casadi as cas
import numpy as np
import pytest

from dist_model_cola_cas.cola_model import (
    M0_DEFAULT,
    NT,
    build_cola_ct_model,
    make_nominal_param_values,
)
from dist_model_cola_cas.cola_lv_model import (
    BS_DEFAULT,
    DS_DEFAULT,
    KCB_DEFAULT,
    KCD_DEFAULT,
    X_SS,
    X_SS_COMP,
    build_cola_lv_ct_model,
    build_cola_lv_sim_function,
    make_nominal_lv_param_values,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def make_param_values(nt=NT):
    """Return a dict of Column A nominal parameter values (numeric DM).

    Thin wrapper kept for backward compatibility with existing tests;
    new tests use make_nominal_param_values() directly.
    """
    from dist_model_cola_cas.cola_model import (
        ALPHA_DEFAULT,
        TAUL_DEFAULT,
        F0_DEFAULT,
        QF0_DEFAULT,
        L0_DEFAULT,
        L0B_DEFAULT,
        LAM_DEFAULT,
        V0_DEFAULT,
        V0T_DEFAULT,
    )

    return {
        "alpha": cas.DM(ALPHA_DEFAULT),
        "taul": cas.DM(TAUL_DEFAULT),
        "F0": cas.DM(F0_DEFAULT),
        "qF0": cas.DM(QF0_DEFAULT),
        "L0": cas.DM(L0_DEFAULT),
        "L0b": cas.DM(L0B_DEFAULT),
        "lam": cas.DM(LAM_DEFAULT),
        "V0": cas.DM(V0_DEFAULT),
        "V0t": cas.DM(V0T_DEFAULT),
        "M0": cas.DM(M0_DEFAULT * np.ones(nt)),
    }


def call_f(model, t, x, u):
    """Evaluate model.f and return xprime as a 1-D numpy array."""
    param_vals = make_param_values()
    result = model.f(
        cas.DM(t),
        cas.DM(x),
        cas.DM(u),
        *param_vals.values(),
    )
    return np.array(result).flatten()


# ---------------------------------------------------------------------------
# Nominal inputs
# ---------------------------------------------------------------------------

U_NOM = np.array([2.70629, 3.20629, 0.5, 0.5, 1.0, 0.5, 1.0])


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def model():
    return build_cola_ct_model()


def test_model_dimensions(model):
    assert model.n == 82
    assert model.nu == 7
    assert model.ny == 82


def test_model_param_names(model):
    assert list(model.params.keys()) == [
        "alpha",
        "taul",
        "F0",
        "qF0",
        "L0",
        "L0b",
        "lam",
        "V0",
        "V0t",
        "M0",
    ]


def test_model_input_names(model):
    assert model.input_names == ["LT", "VB", "D", "B", "F", "zF", "qF"]


def test_f_uniform_state_nominal_inputs(model):
    """Case 1: X = 0.5*ones(82), nominal U.

    Reference xprime from Octave/colamod.m:
      - dxdt[0]  = -0.641258  (reboiler)
      - dxdt[40] = +0.641258  (condenser)
      - all other entries = 0
    """
    x = 0.5 * np.ones(2 * NT)
    xprime = call_f(model, t=0.0, x=x, u=U_NOM)

    assert xprime.shape == (82,)

    # Reboiler and condenser composition derivatives
    assert xprime[0] == pytest.approx(-0.641258, rel=1e-5)
    assert xprime[40] == pytest.approx(0.641258, rel=1e-5)

    # All other entries should be zero
    mask = np.ones(82, dtype=bool)
    mask[0] = False
    mask[40] = False
    assert np.allclose(xprime[mask], 0.0, atol=1e-10)


def test_f_linear_profile_nominal_inputs(model):
    """Case 2: linear composition profile 0.1→0.9, M=M0, nominal U.

    Reference xprime generated by Octave/colamod.m (compositions only;
    all holdup derivatives are zero because M = M0).
    """
    x_comp = np.linspace(0.1, 0.9, NT)
    x = np.concatenate([x_comp, M0_DEFAULT * np.ones(NT)])
    xprime = call_f(model, t=0.0, x=x, u=U_NOM)

    # All holdup derivatives must be zero when M = M0 and lam = 0
    assert np.allclose(xprime[NT:], 0.0, atol=1e-10)

    # Composition derivatives — reference values from Octave
    xprime_comps_ref = np.array(
        [
            -0.1265732571,
            -0.0245942221,
            -0.02136345907,
            -0.01822243946,
            -0.01516786993,
            -0.01219660684,
            -0.009305648157,
            -0.006492125869,
            -0.003753298862,
            -0.001086546251,
            0.001510638902,
            0.004040655472,
            0.006505799823,
            0.008908271013,
            0.0112501757,
            0.01353353277,
            0.01576027769,
            0.01793226658,
            0.02005128013,
            0.02211902722,
            -0.01586285161,
            -0.01389278095,
            -0.01196924739,
            -0.01009079665,
            -0.008256030814,
            -0.006463605725,
            -0.004712228538,
            -0.003000655378,
            -0.001327689132,
            0.0003078226462,
            0.001906989718,
            0.003470881046,
            0.005000526578,
            0.006496918946,
            0.007961015077,
            0.009393737718,
            0.0107959769,
            0.01216859131,
            0.01351240961,
            0.0148282317,
            0.1068763333,
        ]
    )
    assert np.allclose(xprime[:NT], xprime_comps_ref, rtol=1e-6)


def test_f_linear_profile_perturbed_reflux(model):
    """Case 3: linear composition profile 0.1→0.9, M=M0, LT=3.0 (perturbed).

    Compared to case 2, the increased reflux causes:
      - tray 39 holdup to increase  (+0.29371 kmol/min)
      - condenser holdup to decrease (-0.29371 kmol/min)
    Reference values from Octave/colamod.m.
    """
    x_comp = np.linspace(0.1, 0.9, NT)
    x = np.concatenate([x_comp, M0_DEFAULT * np.ones(NT)])
    u = U_NOM.copy()
    u[0] = 3.0  # perturb LT

    xprime = call_f(model, t=0.0, x=x, u=u)

    # Holdup derivatives: only trays 39 and 40 are non-zero
    assert np.allclose(xprime[NT : NT + 39], 0.0, atol=1e-10)
    assert xprime[NT + 39] == pytest.approx(0.29371, rel=1e-4)
    assert xprime[NT + 40] == pytest.approx(-0.29371, rel=1e-4)

    # Composition derivatives — reference values from Octave
    xprime_comps_ref = np.array(
        [
            -0.1265732571,
            -0.0245942221,
            -0.02136345907,
            -0.01822243946,
            -0.01516786993,
            -0.01219660684,
            -0.009305648157,
            -0.006492125869,
            -0.003753298862,
            -0.001086546251,
            0.001510638902,
            0.004040655472,
            0.006505799823,
            0.008908271013,
            0.0112501757,
            0.01353353277,
            0.01576027769,
            0.01793226658,
            0.02005128013,
            0.02211902722,
            -0.01586285161,
            -0.01389278095,
            -0.01196924739,
            -0.01009079665,
            -0.008256030814,
            -0.006463605725,
            -0.004712228538,
            -0.003000655378,
            -0.001327689132,
            0.0003078226462,
            0.001906989718,
            0.003470881046,
            0.005000526578,
            0.006496918946,
            0.007961015077,
            0.009393737718,
            0.0107959769,
            0.01216859131,
            0.01351240961,
            0.0265766317,  # differs from case 2 due to perturbed LT
            0.1068763333,
        ]
    )
    assert np.allclose(xprime[:NT], xprime_comps_ref, rtol=1e-6)


# ---------------------------------------------------------------------------
# LV closed-loop model tests
# ---------------------------------------------------------------------------

# Nominal external inputs for the LV model: [LT, VB, F, zF, qF]
U_LV_NOM = np.array([2.70629, 3.20629, 1.0, 0.5, 1.0])


@pytest.fixture(scope="module")
def lv_model():
    return build_cola_lv_ct_model()


def test_lv_model_dimensions(lv_model):
    assert lv_model.n == 82
    assert lv_model.nu == 5
    assert lv_model.ny == 84


def test_lv_model_input_names(lv_model):
    assert lv_model.input_names == ["LT", "VB", "F", "zF", "qF"]


def test_lv_model_param_names(lv_model):
    assert list(lv_model.params.keys()) == [
        "alpha",
        "taul",
        "F0",
        "qF0",
        "L0",
        "L0b",
        "lam",
        "V0",
        "V0t",
        "M0",
        "KcD",
        "KcB",
        "Ds",
        "Bs",
    ]


def test_lv_model_f_at_steady_state(lv_model):
    """At the Octave-computed steady state the closed-loop RHS is ~zero."""
    param_vals = make_nominal_lv_param_values()
    result = lv_model.f(
        cas.DM(0.0), cas.DM(X_SS), cas.DM(U_LV_NOM), *param_vals.values()
    )
    xprime = np.array(result).flatten()
    assert np.linalg.norm(xprime) < 1e-6


def test_lv_model_controller_gains(lv_model):
    """At perturbed holdup the P-controllers produce the correct D and B.

    With M[0]=0.6 (reboiler +0.1) and M[40]=0.4 (condenser -0.1):
        B = 0.5 + 10*(0.6-0.5) = 1.5
        D = 0.5 + 10*(0.4-0.5) = -0.5  (negative — unphysical, but tests sign)
    At steady-state compositions, the holdup balances give:
        dMdt[0]  ≈ -1.0  (extra bottoms outflow of 1.0 due to B=1.5 vs 0.5)
        dMdt[40] ≈ +1.0  (reduced distillate outflow, D=-0.5 vs 0.5)
    """
    x_test = X_SS.copy()
    x_test[NT] = 0.6  # reboiler holdup perturbed +0.1
    x_test[2 * NT - 1] = 0.4  # condenser holdup perturbed -0.1

    param_vals = make_nominal_lv_param_values()
    result = lv_model.f(
        cas.DM(0.0), cas.DM(x_test), cas.DM(U_LV_NOM), *param_vals.values()
    )
    xprime = np.array(result).flatten()

    assert xprime[NT] == pytest.approx(-1.0, abs=1e-4)
    assert xprime[2 * NT - 1] == pytest.approx(1.0, abs=1e-4)


# ---------------------------------------------------------------------------
# Steady-state rootfinder test
# ---------------------------------------------------------------------------


def test_steady_state_rootfinder(lv_model):
    """Find the Column A steady state via CasADi rootfinder and compare
    to the Octave/cola_lv.m reference (ode15s, 2000 min).

    The rootfinder solves f_lv(0, x, u_nom, params) = 0 using Newton's
    method with CasADi automatic differentiation for the Jacobian.

    Expected (from Octave simulation, norm(xprime) < 3e-9 at t=2000 min):
      xB = x_ss[0]  ≈ 0.01000  (reboiler / bottoms composition)
      xD = x_ss[40] ≈ 0.99000  (condenser / distillate composition)
      M[i] = 0.5 for all i     (all holdups at nominal)
    """
    param_vals = make_nominal_lv_param_values()

    # Build g(x) = f_lv(0, x, u_nom, params_nom)
    x_sym = cas.SX.sym("x", lv_model.n)
    g_expr = lv_model.f(
        cas.DM(0.0), x_sym, cas.DM(U_LV_NOM), *param_vals.values()
    )
    g_func = cas.Function("g", [x_sym], [g_expr], ["x"], ["g"])

    rf = cas.rootfinder("rf", "newton", g_func)
    x0 = 0.5 * np.ones(lv_model.n)
    x_ss = np.array(rf(x0)).flatten()

    # Residual at solution should be near machine precision
    residual = np.array(g_func(x_ss)).flatten()
    assert np.linalg.norm(residual) < 1e-8

    # Key compositions match Octave reference to 4 decimal places
    assert x_ss[0] == pytest.approx(0.01000, abs=1e-4)  # xB (reboiler)
    assert x_ss[40] == pytest.approx(0.99000, abs=1e-4)  # xD (condenser)

    # All holdups at nominal value
    assert np.allclose(x_ss[NT:], 0.5, atol=1e-6)

    # Full composition profile matches Octave reference to 4 decimal places
    assert np.allclose(x_ss[:NT], X_SS_COMP, atol=1e-4)


# ---------------------------------------------------------------------------
# Simulation function builder test
# ---------------------------------------------------------------------------


def test_build_cola_lv_sim_function():
    """build_cola_lv_sim_function returns a valid CasADi simulation function.

    Builds a 5-step simulation (dt=1 min) and verifies:
      - The function has the expected number of inputs/outputs.
      - A run from the known steady-state initial condition produces a
        trajectory that stays at steady state (change < 1e-6).
    """
    dt = 1.0
    nT = 5
    sim_func, model = build_cola_lv_sim_function(dt=dt, nT=nT)

    assert sim_func.n_in() == 3 + len(model.params)  # t_eval, U, x0, *params
    assert sim_func.n_out() == 2  # X, Y

    param_vals = make_nominal_lv_param_values()
    t_eval = np.linspace(0.0, nT * dt, nT + 1)
    U = np.tile(U_LV_NOM, (nT, 1))

    X, Y = sim_func(
        cas.DM(t_eval), cas.DM(U), cas.DM(X_SS), *param_vals.values()
    )
    X = np.array(X)

    assert X.shape == (nT + 1, model.n)
    assert np.allclose(X, X_SS, atol=1e-6)
